news/urls.py
from django.conf.urls import url
from . import views

app_name = 'news'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^(?P<pk>[0-9]+)$', views.DetailView.as_view(), name='detail'),

    # /news/add
    url(r'^add/$', views.NewsCreate.as_view(), name='news-add'),
]

prj1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^news/', include('news.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.

class News(models.Model):
    title = models.CharField(max_length=100)
    short_text = models.CharField(max_length=1000)
    text = models.CharField(max_length=10000)
    image = models.FileField()

    # for form submit kwargs={'pk': self.pk}
    def get_absolute_url(self):
        return reverse('news:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title + ' : ' + self.text

news/views.py
from django.shortcuts import render, get_object_or_404
from .models import News

from django.views import generic
from .models import News
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# Create your views here.

'''def index(request):
    all_news = News.objects.all();
    return render(request, 'news/index.html', {'all_news': all_news})


def detail(request, news_id):
    news = get_object_or_404(News, pk=news_id)
    return render(request, 'news/detail.html', {'news': news})'''


class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = 'all_news'

    def get_queryset(self):
        return News.objects.all()


class DetailView(generic.DetailView):
    model = News
    template_name = 'news/detail.html'


class NewsCreate(CreateView):
    model = News
    fields = ['title', 'short_text', 'text', 'image']

news/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'news/bootstrap-3.3.7-dist/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'news/style.css' %}">
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'news:index' %}">NEWS PAGE</a>
        </div>

        <ul class="nav navbar-nav">
            <li>
                <a href="{% url 'news:index' %}">ALL NEWS</a>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="{% url 'news:news-add' %}">Add news</a>
            </li>
        </ul>
    </div>
</nav>
{% block body%}

{% endblock %}
</body>
</html>

news/templates/news/detail.html
{% extends 'news/base.html' %}


{% block body %}
    <div class="container-fluid">
        <div class="row">
            <!-- Left Album Info -->
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <img src="{{ news.image.url }}" class="img-responsive">
                        <h1>{{ news.title }}
                        </h1>
                        <h2>{{ news.text }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

news/templates/news/form-template.html
{% for field in form %}
    <div class="form-group">
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

news/templates/news/index.html
{% extends 'news/base.html' %}

{% block body %}
    {% if all_news %}
        {% for news in all_news %}
            <div class="col-md-2">
                <div class="thumbnail">
                    <a href="{% url 'news:detail' news.id %}">
                        <img src="{{ news.image.url }}" class="img-responsive">
                    </a>
                    <div class="caption">
                        <h2>{{ news.title }}</h2>
                        <h4>{{ news.short_text }}</h4>

                        <!-- View Details -->
                        <a href="{% url 'news:detail' news.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h3>You dont have news</h3>
    {% endif %}
{% endblock %}

news/templates/news/news_form.html
{% extends 'news/base.html' %}
{% block body%}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'news/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}